version: '2'
services:
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/
    #  - /starter/node_modules
     